name: "amos_core"
version: "0.0.1"
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

seeds:
  amos_core:
    +database: "{{ env_var('DBT_CORE_DATABASE', 'CORE') }}"
    +schema: REFERENCE
    +quote_columns: false
    +tags: ["reference", "seed", "core"]

models:
  amos_core:
    marts:
      +materialized: table
      +database: "{{ env_var('DBT_CORE_DATABASE', 'CORE') }}"
      +schema: public
      +tags: ["marts", "core"]
