name: "amos_core"
version: "0.0.1"
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

seeds:
  amos_core:
    +schema: REFERENCE
    +quote_columns: false
    +tags: ["reference", "seed", "core"]

models:
  amos_core:
    marts:
      +materialized: table
      +schema: public
      +tags: ["marts", "core"]
      
      metrics:
        +materialized: table
        +schema: metrics
        +tags: ["marts", "metrics", "bi"]
